msm8998-common: vintf: Remove something from the matrix
ERROR: files are incompatible: Device manifest and framework compatibility matrix are incompatible: HALs incompatible. Matrix level = 3. Manifest level = 3. The following requirements are not met:
android.hardware.wifi.hostapd:
    required:
        @1.0-3::IHostapd/default OR
        @1.0-2::IHostapd/default
    provided: IHostapd/default (@1)
android.hardware.wifi.supplicant:
    required:
        @1.2-4::ISupplicant/default OR
        @1.0-3::ISupplicant/default
    provided: ISupplicant/default (@1)
: Success